### ISSUE TITLE
Failed to load the ionic-atom package

### ISSUE THREAD

**Issue by vvaka** [RokkinCat/ionic-atom#19]
[Enter steps to reproduce below:]

1. ...upgrade from 0.190 to 0.192
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [ionic-atom](https://github.com/RokkinCat/ionic-atom) package, v0.3.1

### Stack Trace

Failed to load the ionic-atom package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/vvaka/.atom/packages/ionic-atom/lib/ionic.coffee:4:199)
    at /Users/vvaka/.atom/packages/ionic-atom/lib/ionic.coffee:13:5
    at Object.<anonymous> (/Users/vvaka/.atom/packages/ionic-atom/lib/ionic.coffee:64:5)
    at Object.<anonymous> (/Users/vvaka/.atom/packages/ionic-atom/lib/ionic.coffee:102:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
angularjs-snippets, v0.10.2
autocomplete-plus, v2.9.0
file-icons, v1.5.4
git-difftool, v0.2.5
go-oracle, v0.2.0
go-plus, v3.3.6
ionic-atom, v0.3.1
ionic-framework-snippets, v1.1.0
language-groovy, v0.4.0
language-scala, v1.1.0
monokai, v0.14.0
rest-client, v0.3.1
save-session, vundefined
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by fwartner** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [ionic-atom](https://github.com/RokkinCat/ionic-atom) package, v0.3.1

### Stack Trace

Failed to load the ionic-atom package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/fwartner/.atom/packages/ionic-atom/lib/ionic.coffee:4:199)
    at /Users/fwartner/.atom/packages/ionic-atom/lib/ionic.coffee:13:5
    at Object.<anonymous> (/Users/fwartner/.atom/packages/ionic-atom/lib/ionic.coffee:64:5)
    at Object.<anonymous> (/Users/fwartner/.atom/packages/ionic-atom/lib/ionic.coffee:102:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "jekyll-new-post"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet-atom, v2.3.8
ionic-atom, v0.3.1
linter, v0.12.1
minimap, v4.7.6

# Dev
No dev packages
```
